### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Anselmoo** [mretegan/crispy#54]
As shown in the latest merged common
https://github.com/mretegan/crispy/commit/9e5ac48b45568040133da5a375368dd23ca32534 refactors seem to become important.

Further refactors should be considered?

**Comment by mretegan** [comment]
@Anselmoo, l finally managed to merge the PR. I changed some things because they did not improve the code readability, even though they were more pythonic. Did you use an automated code analysis tool for this?

**Comment by Anselmoo** [comment]
@mretegan 
indeed, I use [Sourcery](https://sourcery.ai), which can also be added just to the CI/CD workflow itself
[SpectraFit](https://github.com/Anselmoo/spectrafit) and be modified via `.yaml` if you don't like specific suggestions.


### ref: https://docs.sourcery.ai/Reference/Configuration/sourcery-yaml/

```yaml
ignore: []

refactor:
  include: []
  skip: []
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: '3.9'

```
